base: /
dependencies:
  - bootstrap-package/full
  - fgtclb/academic-base
  - fgtclb/academic-bite-jobs
  - fgtclb/academic-contacts4pages
  - fgtclb/academic-jobs
  - fgtclb/academic-partners
  - fgtclb/academic-persons
  - fgtclb/academic-persons-edit-inline-profile
  - fgtclb/academic-programs
  - fgtclb/academic-projects
  - fgtclb/academic-study-plan
  - typo3/felogin
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    websiteTitle: ''
  -
    title: German
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    fallbackType: strict
    fallbacks: ''
    websiteTitle: ''
rootPageId: 1
routeEnhancers:
  ProfileListPlugin:
    limitToPages:
      - 201
      - 202
      - 203
  ProfileListAndDetailPlugin:
    limitToPages:
      - 204
  ProfileDetailPlugin:
    limitToPages:
      - 205
  AcademicJobsDetailPlugin:
    limitToPages:
      - 233
  AcademicPrograms:
    limitToPages:
      - 251
      - 252
websiteTitle: 'Academic extensions (TYPO3 v14)'
imports:
  -
    resource: 'EXT:academic_persons/Configuration/Routes/List.yaml'
  -
    resource: 'EXT:academic_persons/Configuration/Routes/ListAndDetail.yaml'
  -
    resource: 'EXT:academic_persons/Configuration/Routes/Detail.yaml'
  -
    resource: 'EXT:academic_jobs/Configuration/Routes/Detail.yaml'
  -
    resource: 'EXT:academic_programs/Configuration/Yaml/Routes.yaml'
