base: /
dependencies:
  - bootstrap-package/full
  - fgtclb/academic-persons-default
  - fgtclb/academic-persons-edit
  - fgtclb/academic-programs
  - fgtclb/academic-partners
  - typo3/felogin
errorHandling:
  -
    errorCode: 403
    errorHandler: LoginRedirect
    loginRedirectTarget: 't3://page?uid=10'
    loginRedirectParameter: return_url
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'Academic extensions (TYPO3 v13)'
