<?php

declare(strict_types=1);

namespace FGTCLB\AcademicsDevSite\Tests\Functional;

use FGTCLB\AcademicsDevSite\Tests\Functional\Support\SeedDefinition;
use FGTCLB\AcademicsDevSite\Tests\Functional\Support\SeedManifest;
use FGTCLB\AcademicsDevSite\Tests\Functional\Support\SqliteFileRowReader;
use PHPUnit\Framework\Attributes\Test;
use SBUERK\TYPO3\Testing\TestCase\FunctionalTestCase;
use TYPO3\CMS\Core\Information\Typo3Version;

/**
 * The committed `sqlite-databases/core-NN.sqlite` snapshot holds what the seed
 * definition says it holds.
 *
 * This is the check that was missing. `sqlite-databases/` is the artifact a
 * fresh clone gets its development instance from, and it is produced by a human
 * running an import and a backup. Twice in this repository it has been produced
 * from an older definition than the one committed next to it, and nothing said
 * so - the instance simply held content that no longer matched the seed, and the
 * disagreement was found by somebody wondering why a page was missing.
 *
 * Nothing here is imported. The snapshot is read as a file, through PDO, and
 * measured with exactly the reduction {@see SeedManifest} was generated with.
 *
 * The check is per core version, because the artifact is: `-t 13` measures
 * `core-13.sqlite` and `-t 14` measures `core-14.sqlite`, and a run only ever
 * looks at the one it was configured for.
 */
final class SnapshotManifestTest extends FunctionalTestCase
{
    /**
     * Nothing is loaded and nothing is imported: the subject is a file next to
     * the repository, not this instance. The instance exists because the class
     * needs a `PACKAGE_ROOT` to find that file from, and because reading YAML
     * through `GeneralUtility::getFileAbsFileName()` needs a booted core.
     */
    protected array $testExtensionsToLoad = [
        'fgtclb/academics-monorepo-dev-site',
    ];

    #[Test]
    public function theCommittedSnapshotMatchesTheManifest(): void
    {
        $snapshot = $this->snapshotFile();
        $this->assertFileExists($snapshot);

        $expected = SeedManifest::load();
        $actual = $expected->measure(new SqliteFileRowReader($snapshot), new SeedDefinition());

        $differences = $expected->differencesTo($actual);
        $this->assertSame(
            [],
            $differences,
            sprintf(
                "\"%s\" does not match the committed manifest:\n  %s\n\n"
                . 'The snapshot is regenerated by importing the seed into the "core-%d" development'
                . ' instance and running "ddev composer sqlite:backup" - see'
                . ' "docs/development/instances.md". A snapshot that was not regenerated after a'
                . ' change to the seed definition is what this test exists to report.',
                basename($snapshot),
                implode("\n  ", $differences),
                (new Typo3Version())->getMajorVersion(),
            ),
        );
    }

    private function snapshotFile(): string
    {
        return sprintf(
            '%s/sqlite-databases/core-%d.sqlite',
            $this->getPackagePath(),
            (new Typo3Version())->getMajorVersion(),
        );
    }

    /**
     * The repository root.
     *
     * `PACKAGE_ROOT` is not a public constant of the testing framework, so the
     * path is derived from this file instead: four levels up from
     * `packages-dev/dev-site/Tests/Functional/`.
     */
    private function getPackagePath(): string
    {
        return dirname(__DIR__, 4);
    }
}
