name: "TYPO3 v11"

on:
  pull_request:
  workflow_dispatch:

jobs:

  code-quality:
    name: "code quality"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1" ]
    permissions:
      # actions: read|write|none
      actions: none
      # checks: read|write|none
      checks: none
      # contents: read|write|none
      contents: read
      # deployments: read|write|none
      deployments: none
      # id-token: read|write|none
      id-token: none
      # issues: read|write|none
      issues: none
      # discussions: read|write|none
      discussions: none
      # packages: read|write|none
      packages: read
      # pages: read|write|none
      pages: none
      # pull-requests: read|write|none
      pull-requests: none
      # repository-projects: read|write|none
      repository-projects: read
      # security-events: read|write|none
      security-events: none
      # statuses: read|write|none
      statuses: none
    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Prepare dependencies for TYPO3 v11"
        run: "Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php-version }} -s composerUpdate"

      - name: "Run PHP lint"
        run: "Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php-version }} -s lintPhp"

      - name: "CGL"
        run: "Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php-version }} -s cgl"

# @todo Disable until correct file header has been determined for extensions.
#      - name: "CGL (header comments)"
#        run: "Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php-version }} -s cglHeader"