name: "TYPO3 v11"

on:
  workflow_dispatch:

jobs:
  disabled:
    name: "disabled on current branch"
    if: ${{ 1 == 2 }}
    runs-on: ubuntu-latest
    steps:
      - name: "disabled"
        run: exit 0
